MIN_CURVATURE_VIOLATION = "MIN_CURVATURE_VIOLATION"
SELF_INTERSECTION = "SELF_INTERSECTION"
PANEL_OVERLAP = "PANEL_OVERLAP"
SYMMETRY_VIOLATION = "SYMMETRY_VIOLATION"
CONTINUITY_ERROR = "CONTINUITY_ERROR"

