"""initial schema

Revision ID: 56167f9c09ba
Revises: 8731d0ae822f
Create Date: 2025-12-12 18:59:44.650724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56167f9c09ba'
down_revision = '8731d0ae822f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
