# tests/fixtures/export_request.py (or in conftest)

import pytest
from app.models.export_request import ExportRequest


@pytest.fixture
def export_request(db, project, completed_snapshot):
    """
    Phase M canonical export request fixture.

    IMPORTANT:
    - id is INTEGER (autogenerated)
    - never pass UUIDs
    - represents export intent, not execution
    """
    req = ExportRequest(
        project_id=project.id,
        snapshot_id=completed_snapshot.id,
        export_type="image",
        options={"format": "png"},
    )
    db.add(req)
    db.commit()
    db.refresh(req)
    return req

